// <auto-generated />
namespace NorthCarolinaTaxRecoveryCalculator.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RefertoUserfromACL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RefertoUserfromACL));
        
        string IMigrationMetadata.Id
        {
            get { return "201211221938255_Refer to User from ACL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
