// <auto-generated />
namespace Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DBGeneratedKeyForProjectsTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBGeneratedKeyForProjectsTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201306240504116_DB Generated Key For Projects Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
