// <auto-generated />
namespace Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class IWillGenerateProjectIDStill : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IWillGenerateProjectIDStill));
        
        string IMigrationMetadata.Id
        {
            get { return "201306240528113_I Will Generate Project ID Still"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
