// <auto-generated />
namespace NorthCarolinaTaxRecoveryCalculator.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ExistingRecords : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExistingRecords));
        
        string IMigrationMetadata.Id
        {
            get { return "201210271654272_Existing Records"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
