// <auto-generated />
namespace NorthCarolinaTaxRecoveryCalculator.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddedPaymentVouchers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedPaymentVouchers));
        
        string IMigrationMetadata.Id
        {
            get { return "201308072309425_Added Payment Vouchers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
