// <auto-generated />
namespace NorthCarolinaTaxRecoveryCalculator.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class IDK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IDK));
        
        string IMigrationMetadata.Id
        {
            get { return "201309131524202_IDK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
