// <auto-generated />
namespace NorthCarolinaTaxRecoveryCalculator.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddingINdexToSortOnINPaymentVoucherEntries : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingINdexToSortOnINPaymentVoucherEntries));
        
        string IMigrationMetadata.Id
        {
            get { return "201309131615441_Adding INdex To Sort On IN PaymentVoucherEntries"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
