// <auto-generated />
namespace NorthCarolinaTaxRecoveryCalculator.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddeddTaxinformationtoPaymentVoucher : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddeddTaxinformationtoPaymentVoucher));
        
        string IMigrationMetadata.Id
        {
            get { return "201309121621444_Addedd Tax information to PaymentVoucher"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
