// <auto-generated />
namespace NorthCarolinaTaxRecoveryCalculator.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ChangePaymentVoucherEntry_IDintoanint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangePaymentVoucherEntry_IDintoanint));
        
        string IMigrationMetadata.Id
        {
            get { return "201309112025143_Change PaymentVoucherEntry_ID into an int"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
