// <auto-generated />
namespace NorthCarolinaTaxRecoveryCalculator.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ChnahedReferencetoprojectfromPaymentVoucher : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChnahedReferencetoprojectfromPaymentVoucher));
        
        string IMigrationMetadata.Id
        {
            get { return "201308072318479_Chnahed Reference to project from Payment Voucher"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
